language: node_js
node_js:
  - "14"
dist: trusty
services:
  - mongodb
  - redis
env:
  global:
    - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm i -f
  - npm run build
script:
  - npm run start
  - sleep 3
  - npm run test
